### PR TITLE
Upstream Sync for Minecraft 1.13

### LINKED ISSUE #4: Crashes with NPE if unknown badges are in the mix
Modmenu crashes with a `NullPointerException` at this access to `badge` in `drawBadge`.
This is because `mod.getBadges()` returns a set containing at least one `null`.

https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/ModBadgeRenderer.java#L28-L37

An implementation for `Mod.getBadges()` is here:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/fabric/FabricMod.java#L226-L229
This field is set here:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/fabric/FabricMod.java#L94-L111
Even tho there are more badges added in other code, no code adds `null`. So it comes from the contructor of `ModMenuData`:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/fabric/FabricMod.java#L335-L339
And that shows us the problem:
https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/util/mod/Mod.java#L153-L155
Here, the getter lambda can return `null`, if the given badge key doesn't exist.

To fix this, this should filter it in some way. It might also be a good idea to report this bug to upstream. I don't know if upsteam is affected or not.

Stack Trace:
```
Caused by: java.lang.NullPointerException
	at com.terraformersmc.modmenu.util.mod.ModBadgeRenderer.drawBadge(ModBadgeRenderer.java:33) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at com.terraformersmc.modmenu.util.mod.ModBadgeRenderer.lambda$draw$0(ModBadgeRenderer.java:29) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_392]
	at com.terraformersmc.modmenu.util.mod.ModBadgeRenderer.draw(ModBadgeRenderer.java:29) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.render(ModListEntry.java:75) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.renderEntry(EntryListWidget.java:28) ~[1.12.2-TRv0.8.2-named-711666161528F3329D7A8C8C611232C03E2D58B845ABA1B8F40897F5800EAE50.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.renderList(ModListWidget.java:246) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at net.minecraft.client.gui.widget.ListWidget.render(ListWidget.java:194) ~[1.12.2-TRv0.8.2-named-711666161528F3329D7A8C8C611232C03E2D58B845ABA1B8F40897F5800EAE50.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:321) ~[modmenu-0.2.0+mc1.12.2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:947) ~[1.12.2-TRv0.8.2-named-711666161528F3329D7A8C8C611232C03E2D58B845ABA1B8F40897F5800EAE50.jar:?]
	... 6 more
```

### LINKED ISSUE #5: Consider updating the User Agent to be different from upstream
Hello, as discussed very briefly on the Discord the User Agent used by the Ornithe ModMenu should probably be different than the one upstream ModMenu uses. All that needs to be done for that is to change the [ModMenu.GIT_REF](https://github.com/OrnitheMC/modmenu/blob/cf37d92d92bf54707adf27db7abad4cb5136f60d/src/main/java/com/terraformersmc/modmenu/ModMenu.java#L36) constant to a new value.

### PR DESCRIPTION
**Pull request by LostLuma**
New features cherry-picked from upstream ModMenu.

Resolves #4.
Resolves #5.

### CODE REVIEW

**Comment by LostLuma** [comment]
This should not be merged yet since there is [an issue](https://github.com/TerraformersMC/ModMenu/issues/714) that needs to be fixed upstream (or in Modrinth?) and then added here.

**Comment by LostLuma** [comment]
Upstream got some bug fixes merged, meaning the issues with this are now resolved. I will update the other PRs I made for the other branches tomorrow.

**Comment by LostLuma** [comment]
And now that's done!
I've tested the changes in game in the latest patch version of every minor version as well.

**Review by SpaceWalkerRS — APPROVED** [review]
I didn't look at it too thorougly, if the changes were accepted in upstream that's good enough for me.

**Pull request merged**
